### ISSUE TITLE
asterisk

### ISSUE THREAD

**Issue by bobbykjack** [makeuseofcode/Video-stabilization-using-OpenCV#1]
Is the asterisk in this line intentional or a typo? I can't see that it makes a difference...

https://github.com/makeuseofcode/Video-stabilization-using-OpenCV/blob/91d89318a688b6cf3e6adbe379fdeb3a74f48005/stabilization.py#L51

**Comment by FINCH285** [comment]
It is not a typo. It is used to unpack the string 'mp4v' into individual characters so that each character becomes an argument to the cv2.VideoWriter_fourcc function. The cv2.VideoWriter_fourcc function expects each character of the FourCC code as a separate argument.

**Comment by bobbykjack** [comment]
Gotcha! So would this be the equivalent of:

`fourcc = cv2.VideoWriter_fourcc('m', 'p', '4', 'v')`

? Either way, thanks for the clarification 👍

**Comment by FINCH285** [comment]
Yes! Both forms accomplish the same result.
